version: 1.0.{build}
image: Visual Studio 2017
configuration: Static Release
build:
  project: lame/vc_solution/build.proj
  parallel: true
  verbosity: minimal
artifacts:
- path: 'build\artifacts\%CONFIGURATION%'
  name: 'lame-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%'
