pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildSolution: 'lame\vc_solution\build.proj'

steps:
- task: NuGetToolInstaller@0

- task: MSBuild@1
  inputs:
    solution: '$(buildSolution)'
    maximumCpuCount: true

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build/bin'
    contents: '**/?(*.exe|*.dll|*.lib)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/lame'
    contents: 'include/lame.h'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'LAME MP3-$(Build.SourceVersion)'

- task: GitHubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: 'henricj'
    repositoryName: 'henricj/lame'
    assets: '$(Build.ArtifactStagingDirectory)/**'

- task: GitHubRelease@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  displayName: 'Update GitHub "Latest" Release'
  inputs:
    gitHubConnection: 'henricj'
    repositoryName: 'henricj/lame'
    assets: '$(System.DefaultWorkingDirectory)/*.zip'
    action: 'edit'
    tagSource: 'manual'
    tag: '$(Build.SourceBranchName)-latest'
    isPreRelease: true
    addChangeLog: false
